---
# Deployment file...
apiVersion: v1
kind: Service
metadata:
  name: demo-wordpress
  labels:
    app.kubernetes.io/name: demo-wordpress
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
#  ports:
#  - port: 8080
#    targetPort: 8080
  selector:
    app.kubernetes.io/name: demo-wordpress
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-wordpress
  labels:
    app.kubernetes.io/name: demo-wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-wordpress
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-wordpress
        app.kubernetes.io/managed-by: Ludo
    spec:
      containers:
      - image: harbor.haas-231.pez.pivotal.io/tbs-created/paas-wordpress:latest
        name: paas-wordpress
        imagePullPolicy: IfNotPresent
        resources: {}
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /wp-admin/install.php
            port: http
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /wp-login.php
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
#        resources:
#          requests:
#            cpu: 200m
#            memory: 384Mi

#        livenessProbe:
#          httpGet:
#            path: /actuator/health/liveness
#            port: 8080
#          initialDelaySeconds: 20
#        readinessProbe:
#          httpGet:
#            path: /actuator/health/readiness
#            port: 8080
#          initialDelaySeconds: 20
